### PR TITLE
Document that replication does not work on default databse

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
@EinKrebs could you please review? 

Also can you please check wit CH team to verify that all default databases use the ordinary DB engine? At least this is the case when using CH k8s operator.

**Comment by EinKrebs** [comment]
[https://clickhouse.tech/docs/en/engines/database-engines/](https://clickhouse.tech/docs/en/engines/database-engines/)
Here, it's said that Atomic engine is used by default.

**Comment by pavolloffay** [comment]
What is the version of CH? 

here is my output:
```
SHOW CREATE DATABASE default

Query id: 368d9324-4c89-4109-98fb-d7132ce0776c

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.7.6 revision 54449.

┌─statement────────────────────────────────┐
│ CREATE DATABASE default
ENGINE = Ordinary │
└──────────────────────────────────────────┘

1 rows in set. Elapsed: 0.003 sec. 
```

**Comment by pavolloffay** [comment]
So the plain docker image uses Atomic engine but the operator sets the default  DB to ordinary https://github.com/Altinity/clickhouse-operator/blob/0926d00a22be23499d633ce455bc5473a9620d15/deploy/operator/clickhouse-operator-install-template.yaml#L2335. I will document this.

**Pull request merged**
